mimetypes:
  text/html: html
  text/markdown: markdown
  text/plain: plain
site:
  baseurl: https://laurent.lourenco.pro
  language: en
zas:
  deploy: docs
  layout: .zas/layout.html
ignore:
  - readme.md
  - docs
