baseURL = 'https://lourenco.pro/'
languageCode = 'en-us'
title = 'Laurent Lourenco'
theme = "hugo-coder"

[params]
  author = "Laurent Lourenco"
  info = "Blockchain Aficionado"
  description = "Laurent Lourenco's online index"
  keywords = "identity"
  avatarurl = "images/llcartoon1.png"
  
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  favicon_32 = "favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"
  touchIcon = "apple-touch-icon.png"

  publishDir = "docs"

# social links
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/laurentlourenco/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/laurentlourenco"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 3
  url = "https://t.me/laurentLourenco"
[[params.social]]
    name = "eMail"
    icon = "fa fa-envelope fa-2x"
    weight = 4
    url = "mailto://laurent.lourenco@protonmail.com"

